### ISSUE TITLE
Set class not fully functional when running under Nashorn

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#658]
Nashorn is the new JavaScript engine in JDK 8 and above, replacing Rhino.

The Set class doesn't work when running under Nashorn (any release I try, but specifically the latest OpenJDK8 or OracleJDK8). I can't full grasp what is happened, but it seems to end up with undefined references to `this` inside the methods of the class.

The following code works fine in Rhino, V8 (nodejs and phantomjs) and SpiderMonkey, but does not run in Nashorn. This is under both Opal 0.6.3 and master.

``` ruby
if RUBY_ENGINE == 'opal'
  %x(
    if (typeof console === 'undefined') {
      console = {
        log: function(str) { print(str); },
        warn: function(str) { print(str); }
      }
    }
  )
end

require 'set'

s = [1, 2, 1].to_set
puts s.entries * ','
```

**Comment by Mogztter** [comment]
I've re-enabled JDK EA builds with Opal 0.8.0 and I'm hitting the same issue on `$to_set` method.
Here the code I'm using: https://gist.github.com/Mogztter/cca4921e561b55046c78#file-array-js-L11843

Basically the equivalent Ruby code is:
```ruby
require 'set'

['', 'DEFAULT'].to_set
```
Node.js output:
```
[self] [ [ '', 'DEFAULT' ] ]
$slice.call(arguments, 1) []
arguments {}
[self].concat(args) [ [ '', 'DEFAULT' ] ]
enum$ [ '', 'DEFAULT' ]
enum$ true
```

Nashorn output:
```
[self] ,DEFAULT
$slice.call(arguments, 1) 
arguments [object Arguments]
[self].concat(args) ,DEFAULT
enum$ ,DEFAULT
enum$ false
array.js:3607:6 Error: [object Object]
array.js:3607:6 Error: [object Object]
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeError.captureStackTrace(NativeError.java:150)
	at jdk.nashorn.internal.scripts.Script$Recompilation$133$114367A$asciidoctor_simple.L:3910$L:3915$L:3924(array.js:3934)
	at jdk.nashorn.internal.scripts.Script$Recompilation$132$106248AA$asciidoctor_simple.L:2465$L:2476$L:3586(array.js:3602)
	at jdk.nashorn.internal.scripts.Script$Recompilation$127$asciidoctor_simple.L:11550$L:11554$TMP_1(array:11584)
	at jdk.nashorn.internal.scripts.Script$Recompilation$124$asciidoctor_simple.L:2264$L:2270$TMP_2(array.js:2334)
	at jdk.nashorn.internal.scripts.Script$Recompilation$122$325764AA$asciidoctor_simple.L:11550$L:11820$TMP_16(array.js:11837)
	at jdk.nashorn.internal.scripts.Script$1$asciidoctor_simple.:program(array.js:11844)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.internal.runtime.Context.evaluateSource(Context.java:1224)
	at jdk.nashorn.internal.runtime.Context.load(Context.java:837)
	at jdk.nashorn.internal.objects.Global.load(Global.java:1532)
	at jdk.nashorn.internal.scripts.Script$array.:program(spec/share/array.js:7)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.tools.Shell.apply(Shell.java:393)
	at jdk.nashorn.tools.Shell.runScripts(Shell.java:322)
	at jdk.nashorn.tools.Shell.run(Shell.java:171)
	at jdk.nashorn.tools.Shell.main(Shell.java:135)
	at jdk.nashorn.tools.Shell.main(Shell.java:111)
```

With Node.js:
 *  `self` is an array `[ '', 'DEFAULT' ]`
 * `[self]` is an array in an array `[ [ '', 'DEFAULT' ] ]`

With Nashorn:
 * `[self]` is `,DEFAULT`

I don't really know if this is an issue in Nashorn or in Opal.
I tried to reduce Opal code, as much as possible, to provide a simple test case to the Nashorn team, but this is not an easy task.

@elia If you want I can help you to setup tests against the Nashorn engine

**Comment by elia** [comment]
> @elia If you want I can help you to setup tests against the Nashorn engine

Would be greatly appreciated!

You think it's possible to add a runner for it? 
https://github.com/opal/opal/tree/master/lib/opal/cli_runners
https://github.com/opal/opal/blob/master/lib/opal/cli_runners.rb
https://github.com/opal/opal/blob/master/lib/opal/cli.rb#L73-L81

**Comment by Mogztter** [comment]
> You think it's possible to add a runner for it? 

Sure, I think this will be straightforward because the JDK provides an executable `jjs` to run JavaScript code.
So basically if the JDK is installed and `jjs` available in the `PATH`, the code will be pretty close to the Node.js runner: https://github.com/opal/opal/blob/master/lib/opal/cli_runners/nodejs.rb#L26

Can you tell me how can I test my runner ? Is `node` binary automatically downloaded/installed ? I do have a Rake task to download and install JDK8 EA and JDK9 EA but I don't know how you want to handle this prerequisite.

Thanks

**Comment by elia** [comment]
Running some specs with it should be sufficient. But maybe we can take the chance and start unit testing cli_runners. 

The testing code lives in tasks/testing.rake if you wanna give it a shot. 

As for fetching the jjs binary I think it's ok to deal with it in .travis.yml directly and give some instruction on how to get the binary if it's missing, I think the node runner does something like that already.

**Comment by elia** [comment]
Since Nashorn is now deprecated I'll close this, happy to reopen if it still makes sense for one reason or another
