### ISSUE TITLE
opal 1.1 regression

### ISSUE THREAD

**Issue by rubys** [opal/opal#2180]
The following used to work.

```
% opal -e 'p 1'
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'source-map'
Require stack:
- /Library/Ruby/Gems/2.6.0/gems/opal-1.1.0/lib/opal/cli_runners/source-map-support.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Library/Ruby/Gems/2.6.0/gems/opal-1.1.0/lib/opal/cli_runners/source-map-support.js:30:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Library/Ruby/Gems/2.6.0/gems/opal-1.1.0/lib/opal/cli_runners/source-map-support.js',
    'internal/preload'
  ]
}
```

**Comment by tobymao** [comment]
i've had to roll back the release as well, i'm not able to run my app in mini-racer, i can submit a more detailed report if the future patches doesn't fix it

**Comment by elia** [comment]
@rubys can you try with v1.1.1.rc1 and see if it's fixed? https://rubygems.org/gems/opal/versions/1.1.1.rc1

**Comment by rubys** [comment]
Works on Ubuntu 20.04 and Mac Big Sur.  If there is interest, I can try it on Windows 10 tomorrow.

Unfortunately for me, this bug wasn't the one blocking me; it is #2181 that is preventing me from upgrading.

**Comment by elia** [comment]
Fixed by #2182
