### ISSUE TITLE
def foo(bar = block, &block) gives NoMethodError

### ISSUE THREAD

**Issue by elia** [opal/opal#847]
ref https://github.com/opal/opal/pull/846#issuecomment-101219856
cc @adambeynon

**Comment by elia** [comment]
```
$ ruby -ve 'def foo(a = b, &b) a end; foo {123}'
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
-e:1:in `foo': undefined local variable or method `b' for main:Object (NameError)
Did you mean?  b
	from -e:1:in `<main>'
```

apparently ruby changed its mind, unless it's a bug of course

cc @vais @eregon

**Comment by eregon** [comment]
@elia I can't get the code to work on any version >= 2.0.
I would not rely on this working, nothing guarantees the block parameter is set before the other arguments, I would even expect the opposite by intuition.
IMHO the `proc ||= block` is good enough.

**Comment by elia** [comment]
@eregon :+1: perfect, that's what I expected :smiley:
