### ISSUE TITLE
redefining method on ::Object works oddly

### ISSUE THREAD

**Issue by catmando** [opal/opal#1475]
Pretty obscure but still...

``` ruby
require 'spec_helper'

class ::Object

  define_method :some_bar do
    "bar1"
  end

  def some_bar
    "bar2"
  end

end

describe "TestMethod" do

  it 'you can redefine a method' do
    expect("string".some_bar).to eq("bar2")
  end

end
```

Fails ("string".some_bar) is equal to "bar1"

Works fine for some random class, just not ::Object

Was working in 0.8 as well.

**Comment by elia** [comment]
A reduced example:

```rb
class ::Object
  define_method :some_bar do
    "bar1"
  end

  def some_bar
    "bar2"
  end
end


p Object.new.some_bar # => "bar2"
p "asdf".some_bar # => "bar1"
```

Looks like an issue with `Opal.defn` not updating bridged classes correctly.

**Comment by hmdne** [comment]
In Opal 1.1... the problem changed a bit.

Everything works as expected if you do `class Object`, but `class ::Object` makes every method defined there ignored. Same goes with `class ::String`:

```ruby
>> class ::String; def x; end; end
=> "x"
>> "x".x
x: undefined method `x' for "x"
```

It seems to me as a different bug. The generated code differs in both cases:

For `::String`:

```js
  return (function($base, $super, $parent_nesting) {
    var self = $klass($base, $super, 'String');
  })('::', null, $nesting)
```

For `String`:

```js
  return (function($base, $super, $parent_nesting) {
    var self = $klass($base, $super, 'String');
  })($nesting[0], null, $nesting)
```

Let's try to bisect it better...

```ruby
>> `Opal.klass(null, null, "String")`
=> String
>> `Opal.klass("::", null, "String")`
=> String::String
>>
```

And this gives us some idea now :D
