### ISSUE TITLE
Volt rspec error with 0.9.0.dev

### ISSUE THREAD

**Issue by djboardman** [opal/opal#1111]
I'm getting an error when running the Volt rspecs against 0.9.0.dev (with opal-rspec 0.4.3)

```
NoMethodError: undefined method `delegate_to_metadata' for undefined
```

As far as I can tell this first appears in f73f766b261b881e6cd3256287b8afa28af99693

**Comment by wied03** [comment]
@djboardman - just an FYI, a lot of work is happening in my opal-rspec branch to at least get opal-rspec using 3.1. As part of that effort, a lot of fixes were made to work with opal-0.8. Not saying this isn't an issue (I haven't tested opal-rspec against opal 0.9 yet) but just thought I would let you know.

**Comment by wied03** [comment]
@djboardman - I just tried to run my 0.5 beta specs against Opal 0.9 and encountered another issue before I could even get to where you are. Maybe later on in the week I can do more testing with Opal 0.9

**Comment by elia** [comment]
I reduced the error to this:

```rb
module Foo
  class << self
    def self.bar
      p :bar
    end
    
    bar
  end
end
```

which would produce: 
```
NoMethodError: undefined method `bar' for 
```

The same happens without the `self.`:

```rb
module Foo
  class << self
    def bar
      p :bar
    end
    
    bar
  end
end
# => NoMethodError: undefined method `bar' for 
```

Most probably is the `Opal.defs` that has some problems.

**Comment by elia** [comment]
Just for the record, the extended  test case I used for #1148 is:

```rb
class Foo
  def foo
    p :foo
  end

  define_method :foo2 do
    p :foo2
  end
end

class << Foo
  def self.bar
    p :bar
  end
  bar

  define_singleton_method :bar2 do
    p :bar2
  end
  bar2

  def baz
    p :baz
  end

  define_method :baz2 do
    p :baz2
  end
end
puts
Foo.new.foo
Foo.new.foo2
Foo.singleton_class.bar
Foo.singleton_class.bar2
Foo.baz
Foo.baz2

# >> :bar
# >> :bar2
# >> 
# >> :foo
# >> :foo2
# >> :bar
# >> :bar2
# >> :baz
# >> :bazar
```
