### ISSUE TITLE
[0.10.4] sourcemap not worked for Firefox 52

### ISSUE THREAD

**Issue by zw963** [opal/opal#1681]
[here](https://github.com/zw963/opal-on-rails-example) is a pure bare opal project,

When I run in a chromium Version 56 (64-bit) browser, we can see following logs:

```sh
Started GET "/" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Processing by ColorsController#index as HTML
  Rendering colors/index.html.erb within layouts/application
  Rendered colors/index.html.erb within layouts/application (0.2ms)
Completed 200 OK in 43ms (Views: 42.6ms)


Started GET "/__OPAL_SOURCE_MAPS__/corelib/helpers.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/module.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/class.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/constants.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/basic_object.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/kernel.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/base.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/nil.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/boolean.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/comparable.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/enumerable.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/regexp.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/enumerator.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/string.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/numeric.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/hash.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/array.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/number.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/range.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/proc.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/variables.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/method.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/regexp_anchors.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/mini.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/string/inheritance.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/string/encoding.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/complex.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/time.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/math.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/rational.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/struct.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/io.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/main.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/dir.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/file.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/process.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/unsupported.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/native.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/constants.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/element.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/window.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/document.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/event.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/json.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/promise.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/http.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery/kernel.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal-jquery.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/opal/jquery.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/console.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/abc/color_view_clone.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/application.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/colors_view.self.map" for 127.0.0.1 at 2017-06-15 08:54:07 +0800
Started GET "/__OPAL_SOURCE_MAPS__/corelib/error.self.map" for 127.0.0.1 at 2017-06-15 08:54:08 +0800
```

But, if use firefox, no any source_maps logs output, only:
```
Started GET "/" for 127.0.0.1 at 2017-06-15 08:54:20 +0800
Processing by ColorsController#index as HTML
  Rendering colors/index.html.erb within layouts/application
  Rendered colors/index.html.erb within layouts/application (0.2ms)
Completed 200 OK in 41ms (Views: 40.5ms)
```
sourcemap not worked in firefox 52.1.2

**Comment by zw963** [comment]
I can ensure `sourcemap` feature is enabled in both firefox and chromium.

**Comment by zw963** [comment]
I change some code to make code failed.

Following is chromium output: 
```sh
kernel.rb:1026 Uncaught $NoMethodError {name: "lation_at", message: "undefined method `lation_at' for #<Conway:0x2592>", args: Array[2], stack: "↵    at singleton_class_alloc.TMP_1 [as $new] (htt…1:2000/assets/conway/conway.self.js?body=1:77:20)"}
```

Following is firefox 52 output:

```sh
lation_at: undefined method `lation_at' for #<Conway:0x35c2> (unknown)
```

**Comment by zw963** [comment]
maybe I misunderstood MAP output.

seem like two browser return same map files. (though with different order)

Following is ``Opal::Server`` rackup app log output:

 firefox:

```sh
/
/assets/corelib/runtime.self.js?body=1
/assets/corelib/helpers.self.js?body=1
/assets/corelib/basic_object.self.js?body=1
/assets/corelib/kernel.self.js?body=1
/assets/corelib/module.self.js?body=1
/assets/corelib/class.self.js?body=1
/assets/opal/base.self.js?body=1
/assets/corelib/constants.self.js?body=1
/assets/corelib/error.self.js?body=1
/assets/corelib/boolean.self.js?body=1
/assets/corelib/nil.self.js?body=1
/assets/corelib/string.self.js?body=1
/assets/corelib/regexp.self.js?body=1
/assets/corelib/comparable.self.js?body=1
/assets/corelib/enumerable.self.js?body=1
/assets/corelib/enumerator.self.js?body=1
/assets/corelib/array.self.js?body=1
/assets/corelib/numeric.self.js?body=1
/assets/corelib/hash.self.js?body=1
/assets/corelib/proc.self.js?body=1
/assets/corelib/method.self.js?body=1
/assets/corelib/number.self.js?body=1
/assets/corelib/variables.self.js?body=1
/assets/corelib/range.self.js?body=1
/assets/corelib/string/encoding.self.js?body=1
/assets/corelib/string/inheritance.self.js?body=1
/assets/opal/regexp_anchors.self.js?body=1
/assets/opal/mini.self.js?body=1
/assets/corelib/complex.self.js?body=1
/assets/corelib/math.self.js?body=1
/assets/corelib/time.self.js?body=1
/assets/corelib/io.self.js?body=1
/assets/corelib/main.self.js?body=1
/assets/corelib/rational.self.js?body=1
/assets/corelib/struct.self.js?body=1
/assets/corelib/file.self.js?body=1
/assets/corelib/dir.self.js?body=1
/assets/jquery-1.12.4.min.self.js?body=1
/assets/opal.self.js?body=1
/assets/corelib/unsupported.self.js?body=1
/assets/jquery-migrate-1.4.1.min.self.js?body=1
/assets/corelib/process.self.js?body=1
/assets/opal/jquery/constants.self.js?body=1
/assets/native.self.js?body=1
/assets/opal/jquery/window.self.js?body=1
/assets/opal/jquery/element.self.js?body=1
/assets/json.self.js?body=1
/assets/opal/jquery/http.self.js?body=1
/assets/promise.self.js?body=1
/assets/opal/jquery/event.self.js?body=1
/assets/opal-jquery.self.js?body=1
/assets/opal/jquery/kernel.self.js?body=1
/assets/opal/jquery/document.self.js?body=1
/assets/forwardable.self.js?body=1
/assets/ostruct.self.js?body=1
/assets/opal/jquery.self.js?body=1
/assets/conway/grid.self.js?body=1
/assets/conway/coordinates.self.js?body=1
/assets/console.self.js?body=1
/assets/conway/interval.self.js?body=1
/assets/application.self.js?body=1
/__OPAL_SOURCE_MAPS__/corelib/helpers.self.map
/assets/conway/conway.self.js?body=1
/__OPAL_SOURCE_MAPS__/corelib/basic_object.self.map
/__OPAL_SOURCE_MAPS__/corelib/kernel.self.map
/__OPAL_SOURCE_MAPS__/corelib/class.self.map
/__OPAL_SOURCE_MAPS__/corelib/module.self.map
/__OPAL_SOURCE_MAPS__/corelib/error.self.map
/__OPAL_SOURCE_MAPS__/corelib/constants.self.map
/__OPAL_SOURCE_MAPS__/opal/base.self.map
/__OPAL_SOURCE_MAPS__/corelib/nil.self.map
/__OPAL_SOURCE_MAPS__/corelib/boolean.self.map
/__OPAL_SOURCE_MAPS__/corelib/comparable.self.map
/__OPAL_SOURCE_MAPS__/corelib/string.self.map
/__OPAL_SOURCE_MAPS__/corelib/enumerable.self.map
/__OPAL_SOURCE_MAPS__/corelib/array.self.map
/__OPAL_SOURCE_MAPS__/corelib/enumerator.self.map
/__OPAL_SOURCE_MAPS__/corelib/regexp.self.map
/__OPAL_SOURCE_MAPS__/corelib/numeric.self.map
/__OPAL_SOURCE_MAPS__/corelib/range.self.map
/__OPAL_SOURCE_MAPS__/corelib/method.self.map
/__OPAL_SOURCE_MAPS__/corelib/variables.self.map
/__OPAL_SOURCE_MAPS__/corelib/proc.self.map
/__OPAL_SOURCE_MAPS__/corelib/hash.self.map
/__OPAL_SOURCE_MAPS__/corelib/number.self.map
/__OPAL_SOURCE_MAPS__/opal/regexp_anchors.self.map
/__OPAL_SOURCE_MAPS__/opal/mini.self.map
/__OPAL_SOURCE_MAPS__/corelib/math.self.map
/__OPAL_SOURCE_MAPS__/corelib/string/inheritance.self.map
/__OPAL_SOURCE_MAPS__/corelib/complex.self.map
/__OPAL_SOURCE_MAPS__/corelib/string/encoding.self.map
/__OPAL_SOURCE_MAPS__/corelib/time.self.map
/__OPAL_SOURCE_MAPS__/corelib/rational.self.map
/__OPAL_SOURCE_MAPS__/corelib/dir.self.map
/__OPAL_SOURCE_MAPS__/corelib/file.self.map
/__OPAL_SOURCE_MAPS__/corelib/struct.self.map
/__OPAL_SOURCE_MAPS__/corelib/main.self.map
/__OPAL_SOURCE_MAPS__/corelib/io.self.map
/__OPAL_SOURCE_MAPS__/opal.self.map
/__OPAL_SOURCE_MAPS__/corelib/process.self.map
/__OPAL_SOURCE_MAPS__/corelib/unsupported.self.map
/__OPAL_SOURCE_MAPS__/native.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/element.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/constants.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/document.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/event.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/window.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/kernel.self.map
/__OPAL_SOURCE_MAPS__/json.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/http.self.map
/__OPAL_SOURCE_MAPS__/forwardable.self.map
/__OPAL_SOURCE_MAPS__/opal-jquery.self.map
/__OPAL_SOURCE_MAPS__/console.self.map
/__OPAL_SOURCE_MAPS__/ostruct.self.map
/__OPAL_SOURCE_MAPS__/promise.self.map
/__OPAL_SOURCE_MAPS__/conway/coordinates.self.map
/__OPAL_SOURCE_MAPS__/conway/grid.self.map
/__OPAL_SOURCE_MAPS__/conway/interval.self.map
/__OPAL_SOURCE_MAPS__/conway/conway.self.map
/__OPAL_SOURCE_MAPS__/application.self.map
```

chromium:

```sh
/
/assets/corelib/runtime.self.js?body=1
/assets/corelib/basic_object.self.js?body=1
/assets/corelib/module.self.js?body=1
/assets/corelib/kernel.self.js?body=1
/assets/corelib/helpers.self.js?body=1
/assets/corelib/class.self.js?body=1
/assets/corelib/constants.self.js?body=1
/assets/corelib/nil.self.js?body=1
/assets/corelib/error.self.js?body=1
/assets/opal/base.self.js?body=1
/assets/corelib/regexp.self.js?body=1
/assets/corelib/boolean.self.js?body=1
/assets/corelib/string.self.js?body=1
/assets/corelib/enumerable.self.js?body=1
/assets/corelib/array.self.js?body=1
/assets/corelib/numeric.self.js?body=1
/assets/corelib/comparable.self.js?body=1
/assets/corelib/hash.self.js?body=1
/assets/corelib/range.self.js?body=1
/assets/corelib/enumerator.self.js?body=1
/assets/corelib/number.self.js?body=1
/assets/corelib/method.self.js?body=1
/assets/corelib/proc.self.js?body=1
/assets/corelib/variables.self.js?body=1
/assets/opal/regexp_anchors.self.js?body=1
/assets/corelib/string/encoding.self.js?body=1
/assets/corelib/string/inheritance.self.js?body=1
/assets/corelib/math.self.js?body=1
/assets/corelib/rational.self.js?body=1
/assets/opal/mini.self.js?body=1
/assets/corelib/struct.self.js?body=1
/assets/corelib/complex.self.js?body=1
/assets/corelib/time.self.js?body=1
/assets/corelib/io.self.js?body=1
/assets/corelib/dir.self.js?body=1
/assets/corelib/main.self.js?body=1
/assets/corelib/file.self.js?body=1
/assets/opal.self.js?body=1
/assets/corelib/process.self.js?body=1
/assets/jquery-1.12.4.min.self.js?body=1
/assets/opal/jquery/constants.self.js?body=1
/assets/opal/jquery/element.self.js?body=1
/assets/jquery-migrate-1.4.1.min.self.js?body=1
/assets/native.self.js?body=1
/assets/corelib/unsupported.self.js?body=1
/assets/opal/jquery/document.self.js?body=1
/assets/opal/jquery/window.self.js?body=1
/assets/opal/jquery/event.self.js?body=1
/assets/promise.self.js?body=1
/assets/json.self.js?body=1
/assets/forwardable.self.js?body=1
/assets/opal/jquery.self.js?body=1
/assets/opal/jquery/kernel.self.js?body=1
/assets/opal/jquery/http.self.js?body=1
/assets/ostruct.self.js?body=1
/assets/opal-jquery.self.js?body=1
/assets/conway/grid.self.js?body=1
/assets/conway/coordinates.self.js?body=1
/assets/conway/interval.self.js?body=1
/assets/console.self.js?body=1
/assets/conway/conway.self.js?body=1
/assets/application.self.js?body=1
/__OPAL_SOURCE_MAPS__/corelib/helpers.self.map
/__OPAL_SOURCE_MAPS__/corelib/module.self.map
/__OPAL_SOURCE_MAPS__/corelib/basic_object.self.map
/__OPAL_SOURCE_MAPS__/corelib/kernel.self.map
/__OPAL_SOURCE_MAPS__/corelib/constants.self.map
/__OPAL_SOURCE_MAPS__/corelib/class.self.map
/__OPAL_SOURCE_MAPS__/opal/base.self.map
/__OPAL_SOURCE_MAPS__/corelib/error.self.map
/__OPAL_SOURCE_MAPS__/corelib/nil.self.map
/__OPAL_SOURCE_MAPS__/corelib/string.self.map
/__OPAL_SOURCE_MAPS__/corelib/comparable.self.map
/__OPAL_SOURCE_MAPS__/corelib/enumerable.self.map
/__OPAL_SOURCE_MAPS__/corelib/boolean.self.map
/__OPAL_SOURCE_MAPS__/corelib/regexp.self.map
/__OPAL_SOURCE_MAPS__/corelib/enumerator.self.map
/__OPAL_SOURCE_MAPS__/corelib/array.self.map
/__OPAL_SOURCE_MAPS__/corelib/numeric.self.map
/__OPAL_SOURCE_MAPS__/corelib/hash.self.map
/__OPAL_SOURCE_MAPS__/corelib/range.self.map
/__OPAL_SOURCE_MAPS__/corelib/number.self.map
/__OPAL_SOURCE_MAPS__/corelib/method.self.map
/__OPAL_SOURCE_MAPS__/corelib/proc.self.map
/__OPAL_SOURCE_MAPS__/opal/mini.self.map
/__OPAL_SOURCE_MAPS__/opal/regexp_anchors.self.map
/__OPAL_SOURCE_MAPS__/corelib/string/inheritance.self.map
/__OPAL_SOURCE_MAPS__/corelib/math.self.map
/__OPAL_SOURCE_MAPS__/corelib/string/encoding.self.map
/__OPAL_SOURCE_MAPS__/corelib/time.self.map
/__OPAL_SOURCE_MAPS__/corelib/variables.self.map
/__OPAL_SOURCE_MAPS__/corelib/rational.self.map
/__OPAL_SOURCE_MAPS__/corelib/main.self.map
/__OPAL_SOURCE_MAPS__/corelib/struct.self.map
/__OPAL_SOURCE_MAPS__/corelib/dir.self.map
/__OPAL_SOURCE_MAPS__/corelib/complex.self.map
/__OPAL_SOURCE_MAPS__/corelib/io.self.map
/__OPAL_SOURCE_MAPS__/corelib/process.self.map
/__OPAL_SOURCE_MAPS__/opal.self.map
/__OPAL_SOURCE_MAPS__/corelib/unsupported.self.map
/__OPAL_SOURCE_MAPS__/native.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/element.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/window.self.map
/__OPAL_SOURCE_MAPS__/corelib/file.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/document.self.map
/__OPAL_SOURCE_MAPS__/promise.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/event.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/constants.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/kernel.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery.self.map
/__OPAL_SOURCE_MAPS__/opal-jquery.self.map
/__OPAL_SOURCE_MAPS__/json.self.map
/__OPAL_SOURCE_MAPS__/opal/jquery/http.self.map
/__OPAL_SOURCE_MAPS__/conway/coordinates.self.map
/__OPAL_SOURCE_MAPS__/console.self.map
/__OPAL_SOURCE_MAPS__/forwardable.self.map
/__OPAL_SOURCE_MAPS__/ostruct.self.map
/__OPAL_SOURCE_MAPS__/conway/grid.self.map
/__OPAL_SOURCE_MAPS__/conway/conway.self.map
/__OPAL_SOURCE_MAPS__/conway/interval.self.map
/__OPAL_SOURCE_MAPS__/application.self.map
```

**Comment by zw963** [comment]
sorry, It hard to describe where exists some special behavior ...

example app is here: https://github.com/zw963/conway_gal

maybe could try locally to reveal

usage: 
``rackup`` start server, and then press `C-c` and then press `return` to start play
a game like following in browser

![pic1](http://www.conwaylife.com/w/images/2/21/Lwss.gif)

**Comment by elia** [comment]
@zw963 have you tried this? https://stackoverflow.com/a/41007103

**Comment by elia** [comment]
This seems an error in opal-sprockets and `require_tree` that for some reason loads 3 files after the main one which is supposed to be the last one. I'll investigate it, thanks for the report.

<img width="1041" alt="untitled" src="https://user-images.githubusercontent.com/1051/27984421-fe6a0006-63d5-11e7-8954-d6aade20939b.png">

**Comment by elia** [comment]
@zw963 in the meanwhile you can fix the behavior using this line in application.html.erb:

```erb
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', force_opal_loader_tag: true %>
```

**Comment by zw963** [comment]
> @zw963 have you tried this? https://stackoverflow.com/a/41007103



I have tried ,  i do following diff to this project:

```diff
-  def is_underpopulated?(x, y)
+  def is_underpopulated?(state, x, y)
     is_alive?(x, y) && population_at(x, y) < 2
   end
```

which cause following error log, it not especial useful for me.
(I have no idea for enable arity_check option for Opal::Server).

firefox 52:
```
TypeError: item is undefined[Learn More] array.self.js:1274:11
```

chromium 56:

```
Uncaught TypeError: Cannot read property '$hash' of undefined
    at Array.$$hash [as $hash] (array.rb:1098)
    at Object.Opal.hash_get (runtime.self.js?body=1:1669)
    at $Hash.TMP_6 [as $[]] (hash.rb:121)
    at $Conway.TMP_17 [as $is_alive?] (conway.rb:106)
    at $Conway.TMP_12 [as $is_underpopulated?] (conway.rb:71)
    at $Conway.$$get_state_at [as $get_state_at] (conway.rb:59)
    at TMP_9 (conway.rb:53)
    at Object.Opal.yield1 (runtime.self.js?body=1:1194)
    at $Hash.$$each (hash.rb:273)
    at $Conway.$$new_state [as $new_state] (conway.rb:52)
```

Following maybe a new issue ...

before I switch to use `config.ru` run server, i just use a `rake task`
to compile  application.js and ref it directly in `index.html`. it worked
in my chromium 56.

But, after switch to use `config.ru` and `opal-sporckets` this game 
not worked in chromium 56 anymore, but still worked in firefox 52.

**Comment by zw963** [comment]
> @zw963 in the meanwhile you can fix the behavior using this line in application.html.erb:

I tried, failed. https://github.com/zw963/conway_gal/commit/b98ad6c

this is not a rails project, seem like `javascript_include_tag` not support those arguments

```sh
[2017-07-08 19:11:26] INFO  WEBrick 1.3.1
[2017-07-08 19:11:26] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
[2017-07-08 19:11:26] INFO  WEBrick::HTTPServer#start: pid=10449 port=2000
ArgumentError: wrong number of arguments (given 2, expected 1)
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:109:in `javascript_include_tag'
	index.html.erb:9:in `block in singleton class'
	index.html.erb:-6:in `instance_eval'
	index.html.erb:-6:in `singleton class'
	index.html.erb:-8:in `__tilt_13091820'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:102:in `html'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:92:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-0.10.4/lib/opal/sprockets/server.rb:79:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by elia** [comment]
> (I have no idea for enable arity_check option for Opal::Server).


Add this:

    Opal::Config.arity_check_enabled = true

just before the server definition

**Comment by zw963** [comment]
> Opal::Config.arity_check_enabled = true

Cool, thank you.
before, i only know this compile option, and now, I know this is configable in Opal::Server !
